---
- name: Install and start app
  hosts: app
  become: yes
  vars:
   deploy_user: ubuntu

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Get the latest version app
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith
      notify: restart puma

    - name: Install app
      become: no
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"

  handlers:
  - name: restart puma
    systemd: name=puma state=restarted
