---
- name: Install Ruby
  hosts: all
  become: yes
  tasks:
    - name: Install ruby and bundle
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - ruby-full
        - ruby-bundler
        - build-essential
