---
- hosts: app
  become: yes
  roles:
    - app
    - jdauphant.nginx

- hosts: db
  become: yes
  roles:
    - db

      #- import_playbook: users.yml
- import_playbook: base.yml
- import_playbook: deploy.yml
